### ISSUE TITLE
Computing Environment Error

### ISSUE THREAD

**Issue by K0BigYang** [PHME-Datachallenge/Data-Challenge-2022#23]
Dear Organizer,

We have some problem when we "import tensorflow", likes:
![截圖 2022-06-07 上午1 29 46](https://user-images.githubusercontent.com/17896429/172213661-3ca30baf-1f5b-4fe9-ba52-68ac28d6ec2d.png)

Can you help us to fix it?
Thank you for your help.

Regards,
Kenny Yang

**Comment by HuangChiEn** [comment]
> Very weird. We will investigate.

Could you help us do some 'harmless' hacker way? The following solution in StackOverflow needs to rename the file name of the shared object. 
https://stackoverflow.com/questions/65405705/undefined-symbol-zn10tensorflow8opkernel11tracestringepns-15opkernelcontexteb/67510891#67510891

I have try to rename (instead of delete) the "tensorflow/core/kernels/libtfkernel_sobol_op.so" file name to "tensorflow/core/kernels/libtfkernel_sobol_op_sufix.so", 
(PS. If it's not work, just rename it again back to the original file name)

Of course, I didn't have the priveledges to do that.
![image](https://user-images.githubusercontent.com/52521165/172272965-915c0542-d795-4a67-a229-28d13bd3bf47.png)

The other official solution is also looking forward though.

**Comment by K0BigYang** [comment]
> Very weird. We will investigate.

Dear Organizer,

Because our method needs to use this package.
Could you fix that as soon as possible so that we can be updated on the leaderboard?
Thank you for your help.

Regards,
Kenny Yang

**Comment by marty90** [comment]
`kyang` correctly appears. `tko` does not (there is an exception in importing TensorFlow).

**Comment by K0BigYang** [comment]
> 
Dear Organizer,

Could you recompute it and show the score in there for us?
Thank you for your help.

Regards,
Kenny Yang

**Comment by marty90** [comment]
Did you install locally some version of TensorFlow (e.g., with `pip install --user tensorflow`)?
If yes, delete everything you installed locally, otherwise the dashboard will never work.

**Comment by K0BigYang** [comment]
Okay, I have removed it.

**Comment by alexlange90** [comment]
Hello K0BigYang,

did that solve the problem for you? I am currently using some libraries that I installed within a virtual environment and I am calling that environment from the execution notebook. I am now wondering whether this causes any error, so that my / our scores are not reported on the leaderboard.

**Comment by marty90** [comment]
@K0BigYang , now you are on the leaderboard.

**Comment by K0BigYang** [comment]
> @K0BigYang , now you are on the leaderboard.

@marty90 Thanks for your help.
