### ISSUE TITLE
Potential flaw in model 2 and 3 evaluation

### ISSUE THREAD

**Issue by klopetx** [PHME-Datachallenge/Data-Challenge-2022#9]
Working for solutions to the problem you have proposed for this year, we believe we might have found a strange behaviour of the evaluation system that we do not know for sure whether it occurs in purpose or by chance.

The point is that during the evaluation of the models 2 and 3, the target is considered the AOI file, and each row is considered an observation.

However, AOI dataset contains duplicated Panel, Figure and Component combinations, as some components (even some pins) can suffer various failures at a time. Nevertheless, the code used for the validation (in particular the following lines) forces the output of the prediction of models 2 and 3 to be sets, which have unique identifiers. This means that, even if different predictions are provided (for example for different pins of the AOI), when the identifiers already exist only the last one is used (see the following example).

![phme_possible fault](https://user-images.githubusercontent.com/44928830/165778715-50e9eb25-c924-4001-98fb-ee7222302f9d.png)

So, even if the evaluation looks for every line of the AOI (which includes duplicated Panel, Figure, Components), in practice, the prediction is only allowed to provide a single label for each combination (which means it will most probably fail when there are duplicates).

We are not sure if this is intended or not, but maybe this behaviour might be avoided by allowing the user to provide a vector with a length equivalent to the number of rows of the AOI and comparing this to the real one.

Looking forward to hearing from you,

Thanks and best regards,

klopetx

**Comment by dgiordan88** [comment]
Dear Kerman,

There must be a single row for each component. 
In the AOI dataset there can be multiple rows for the same component - see figures below. 

For the first label (AOILabel), you just need to predict that the component exists in the AOI dataset. 
Even if the AOILabel takes 2 values (e.g. in the first example), this is not a problem, because you only need to predict if the component is present in the AOI dataset. I.e., the existence of component D1 in the AOI dataset.

The other labels (OperatorLabel and RepairLabel) are always the same for all lines belonging to the same component (e.g. both examples). 
Therefore, it is necessary to predict only a single row.

In the evaluation test, we will perform this kind of evaluation for each component. 
So the line marked with the black box in your example is impossible. It implies that one component (i.e., D1) will be given 2 different labels in the operator. 
Did you insert this line to show me an example, right? Because according to our script it should not be there.

Thanks a lot!

![Schermata 2022-04-29 alle 17 02 11](https://user-images.githubusercontent.com/15250393/165973322-1f450765-560c-43b0-a6d0-bcbf3653cf41.png)

![phme_possible fault](https://user-images.githubusercontent.com/15250393/165973395-84b68519-4cc5-4dbf-8b5b-855d54232c5f.png)

**Comment by klopetx** [comment]
Your are right, AOI rows belonging to same component always have the same Operator and Repair label.

My fault, thanks for the clarification!
